//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEC06.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OECContext : DbContext
    {
        public OECContext()
            : base("name=OECContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<crop> crops { get; set; }
        public virtual DbSet<farm> farms { get; set; }
        public virtual DbSet<fertilizer> fertilizers { get; set; }
        public virtual DbSet<plot> plots { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<treatment> treatments { get; set; }
        public virtual DbSet<treatmentFertilizer> treatmentFertilizers { get; set; }
        public virtual DbSet<variety> varieties { get; set; }
    }
}
